### PR TITLE
Add command params to control retries of failed API requests

### LINKED ISSUE #69: Backoff when replication or API request error
Should a construct be added so that an exponential backoff occurs when there is a replication or API request error? Currently, when an error is encountered, Spiegel will put the item back in the queue and retry it. This is fine when the errors are transient and ideally all these errors would be transient, but if the error is permanent then Spiegel will _waste_ significant resources until the error can be resolved.

It may be ideal to implement the [dirty_after_milliseconds](https://github.com/redgeoff/spiegel/issues/53) enhancement first so that it can be used here

### PR DESCRIPTION
**Pull request by bleachy**
This PR adds the ability to throttle the retries of failed API requests. In the current version these will replay indefinitely with minimal delay, until the API comes back up. But this causes significant cpu resource to be consumed.

With this PR we can use a linear backoff to set a constant interval in between retry attempts, or specify an exponential backoff with optional multiplier to use on each interval. We can also choose to either replay indefinitely or set a limit on the number of retries to attempt, before moving on.

Fixes: #69

### CODE REVIEW

**Review by redgeoff — APPROVED** [review]
This is a very nice addition! Thanks, @bleachy

**Comment by bleachy** [comment]
Thanks for merging this @redgeoff. Could you create a new release and docker build for master as well please if possible?

**Comment by redgeoff** [comment]
Sure, I'll try to get to this next week. Sorry for the wait!

**Comment by redgeoff** [comment]
@bleachy [v1.2.0](https://github.com/redgeoff/spiegel/releases/tag/v1.2.0) is now on npm and docker hub.

**Comment by bleachy** [comment]
Amazing. Thanks @redgeoff 🙌

**Pull request merged**
