### PR TITLE
on_change support $variables in the url's path similar to parameters #171

### PR DESCRIPTION
**Pull request by lostnet**
This is the parsing and some unit test changes for the parsing I suggested, using regexes. Since it uses a lookbehind regex it requires node 8.10.0 or above.

### CODE REVIEW

**Comment by lostnet** [comment]
On the CI tests issue, shortening the number of keys in this request seems to eventually get from a 400 to a 200 response [when shortening it bellow 1460 characters ](https://github.com/apache/couchdb/issues/1810):

`\"href\":\"http://admin:admin@localhost:5984/test_spiegel_integration1545778694804/_design/clean_or_locked_replicators_by_db_name/_view/clean_or_locked_replicators_by_db_name?include_docs=true&keys=%5B%22test_spiegel1545759505571%22%2C%22test_db1_1545759505584_9%22%2C%22test_db2_1545759505584_12%22%2C%22test_db2_1545759505584_14%22%2C%22test_db2_1545759505584_16%22%2C%22test_db1_1545759505584_18%22%2C%22test_spiegel1545759536748%22%2C%22test_db1_1545759505584_25%22%2C%22test_db3_1545759505584_7%22%2C%22test_db1_1545759505584_11%22%2C%22test_db1_1545759505584_13%22%2C%22test_db1_1545759505584_15%22%2C%22test_db3_1545759505584_17%22%2C%22test_db2_1545759505584_19%22%2C%22test_db1_1545759505584_20%22%2C%22test_db2_1545759505584_21%22%2C%22test_db1_1545759505584_7%22%2C%22test_db3_1545759505584_9%22%2C%22test_spiegel1545759538289%22%2C%22test_spiegel1545759539814%22%2C%22test_spiegel1545759546128%22%2C%22test_db1_1545759505584_23%22%2C%22test_db3_1545759505584_23%22%2C%22test_spiegel1545759541258%22%2C%22test_spiegel1545759544657%22%2C%22test_spiegel1545759543224%22%2C%22test_db1_1545759505584_22%22%2C%22test_db3_1545759505584_22%22%2C%22test_db1_1545759505584_24%22%2C%22test_db3_1545759505584_25%22%2C%22test_db1_1545759505584_29%22%2C%22test_db3_1545759505584_29%22%2C%22test_db1_1545759505584_31%22%2C%22test_db3_1545759505584_31%22%2C%22test_db1_1545759505584_35%22%2C%22test_spiegel_integration1545759560095%22%2C%22test_db1_1545759637510_7%22%2C%22test_db3_1545759637510_9%22%2C%22test_db3_1545759505584_24%22%2C%22test_db1_1545759505584_28%22%2C%22test_db3_1545759505584_28%22%2C%22test_db1_1545759505584_34%22%2C%22test_db3_1545759505584_34%22%2C%22test_db1_1545759505584_27%22%2C%22test_db2_1545759637510_14%22%2C%22test_db3_1545759505584_27%22%5D`

setting recbuf on my couchdb's chttpd seems to fix the test.

**Comment by redgeoff** [comment]
Nice find! I think we may be able to restrict the batch size until this bug is fixed

**Comment by redgeoff** [comment]
This looks great! I've fixed the tests by fixing the CouchDB version to 2.2 until https://github.com/apache/couchdb/issues/1810 has been fixed. Can you please merge with master to update this PR?

Also, can you please update the _Notes_ section at https://github.com/redgeoff/spiegel/blob/master/DESIGN.md#on_change to include details of this change. Thanks!

**Comment by lostnet** [comment]
@redgeoff I tried to add the changes to DESIGN.md, and I also realized some edge cases like multiple end braces could exist in the static parameters when declared in the on_changes docs (even if they might be urlencoded based on the method later,) so I changed the way ${variables} are normalized to make sure it doesn't interfere and added some testing of edge case in the parameters.

Please take a look and let me know what you think, thanks!

**Comment by redgeoff** [comment]
Nice work @lostnet! I just merged it, thanks!

**Pull request merged**
