### PR TITLE
Add dirty_after_milliseconds option to replicators

### LINKED ISSUE #53: Support for dirty_after_milliseconds in replicator
Currently, the replicator's `dirty` flag is used to immediately schedule a replication. Duplicate requests are debounced, but we may want to be less aggressive with replications. In this case we could support a `dirty_after_milliseconds` attribute in the replicator. If `dirty_after_milliseconds` then instead of setting `dirty=true` we could set `dirty_at` to a value. Then, we can create a routine (backed by a view) that checks for all replicators with `dirty_at` specified and then only sets `dirty=true` at the appropriate time.

### PR DESCRIPTION
**Pull request by jjd314**
Replicators with dirty_after_milliseconds > 0 will delay setting the dirty flag
by that amount, to reduce replication burden on rapidly changing databases

Fixes #53

### CODE REVIEW

**Comment by redgeoff** [comment]
I think this is on the right track, but there are few things to consider. 

I see that the requeuing happens at https://github.com/redgeoff/spiegel/pull/146/files#diff-ae9f681f369fdd1a7c7ec9ce72b88f37R166, but the problem with this is that it means that only one of the processes is doing this and there could be many. We need a mechanism to spread the load to other processes and account for processes crashing etc...

I think a more robust design would use a [continuous iterator](https://github.com/redgeoff/slouch/wiki/Don%27t-just-relax.-Slouch%21#example-4---continuously-process-all-changes-to-a-db) on a view call similar to https://github.com/redgeoff/spiegel/pull/146/files#diff-5edced2e9374281a2f0943cee8967525R527. This would result in an item whenever a dirty_at is changed. You could then use something like `this._runSoilerAt` and the item's dirty_at to determine whether to change the time before the soiler is next run.

Here is some pseudo code:
```js

_dirtyAtItems(opts) {
  return this._slouch.db.view(
    this._spiegel._dbName,
    '_design/dirty_at_' + this._type,
    'dirty_at_' + this._type,
    { include_docs: true, ...opts }
  )
}

_soilPendingItems() {
  // Use _dirtyAtItems without continuous to iterate through all items and dirty them when
  // appropriate. If there are more items with dirty_at then set this._runSoilerAt accordingly;
  // otherwise, set this._runSoilerAt to null. 
}

_queueSoiler() {
  // The soiler routine needs to be able to run at intervals that can change at any point so we have
  // use setTimeout for a short interval with a check for the dynamic interval. This design also
  // ensures that we have only one instance of _soilPendingItems running at any given time so that
  // we don't create conflicts with ourself.
  this._soiler = setTimeout(() => {
    if (this._runSoilerAt !== null && (new Date()).getTime() > this._runSoilerAt.getTime()) {
      this._soilPendingItems();
    }
    this._queueSoiler();
  }, 300000)
}

_listenToDirtyAtChanges() {
  this._dirtyAtIterator = _dirtyAtItems({ feed: 'continuous' }); // Note: the continuous
  this._dirtyAtIterator.each(change => {
    // Analyze change and set this._runSolierAt if change.doc.dirtyAt is before
  })
}

async start() {
  ...

  this._startUnstaller()

  this._listenToDirtyAtChanges();

  this._queueSoiler();
}
```

**Comment by redgeoff** [comment]
Another thing that I think you have to worry about is that when there is an attempt to dirty an item that has a dirty_at, via the normal process and not the soiler, the item probably shouldn't be dirtied. Otherwise, a new change would trigger the dirtying and clear out any `dirty_after_milliseconds`

**Comment by jjd314** [comment]
Thanks for the comments.  I'm heading on vacation, though, so it'll be a couple of weeks before I get back to this (and the other ones).

**Comment by jjd314** [comment]
Just FYI, I'm back and working on this (and the others) again.  All my working memory of how any of this works or what I was doing was completely erased by my trip, though, so progress will be slow.

**Comment by jjd314** [comment]
Quick question: how can I run a single test, or even a single test file?  When I try `npm run node-test test/spec/process` I get errors about databases not existing.

**Comment by jjd314** [comment]
I added the continuous iterator.  I did not go with the two-step timeout process: I just modified the setup I had in place to calculate the appropriate delay and reset the timeout as necessary.  Also, per your comment about dirtying via the normal process, I think that is already handled in replicators.js: if there is a dirty_after_milliseconds value, it doesn't try to set the dirty flag directly.

**Comment by redgeoff** [comment]
Cool! I’ll take a look after I get back from vacation

**Comment by redgeoff** [comment]
Nice @jjd314! This looks good.

Your clearTimeout() logic is an improvement over my suggested design.

I agree that my concern about the dirty_after_milliseconds should not be an issue.

Can you please resolve the conflicts so that we can get this merged?

**Comment by jjd314** [comment]
I fixed the test that I broke, but I don't know why the "after hook" is failing in the integration test.

**Comment by redgeoff** [comment]
My guess is that the listening on the new continuous listener is not being aborted in https://github.com/redgeoff/spiegel/blob/c403ddc99bdb0ec9fecfdaa2e6f1741cec18d464/src/process.js#L469

**Comment by jjd314** [comment]
It seems I do not understand how that all works.  I added a call to abort() the _dirtyAtListener in stop(), but I still get the same behavior.  If I put a console.log into _stopListeningToDirtyAtChanges(), I instead get this error:
```
       integration
         "after each" hook:
     Uncaught Error: Invalid JSON (Unexpected "A" at position 0 in state STOP)
      at Parser.proto.charError (node_modules/jsonparse/jsonparse.js:90:16)
      at Parser.proto.write (node_modules/jsonparse/jsonparse.js:154:23)
      at Stream.<anonymous> (node_modules/JSONStream/index.js:21:12)
      at Stream.stream.write (node_modules/through/index.js:26:11)
      at Socket.ondata (_stream_readable.js:639:20)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at Pipe.onread (net.js:597:20)
```

Any advice?

**Comment by redgeoff** [comment]
The changes you made to stop the listening look good. The invalid JSON is typical when you abort a feed.

I'll try to take a closer look soon.

**Comment by redgeoff** [comment]
Sorry, it has been a while on this. I recently updated Spiegel to use PouchDB 7 and there appears to be a listener leak that causes the tests to hang. Until PouchDB is patched we can workaround this with a SIGTERM signal: https://github.com/redgeoff/spiegel/pull/160/files#diff-e9e4800ce6754de575efb451bba55c9bR99. I'm thinking that the issue you are seeing is probably because PouchDB 6 also suffers from this problem and it is a race condition so it has just surfaced with your new code.

I think you should be able to merge with master to resolve the issue.

**Comment by redgeoff** [comment]
Merged, thanks @jjd314!

**Pull request merged**
